version: '3.7'
services:
  db:
    image: mariadb:10.1-bionic
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./.env
    ports:
      - ${MARIADB_PORT}:3306
    networks:
      default:
        aliases:
          - db

  concrete5:
    build:
      context: .
      args:
        CONCRETE5_VERSION: $CONCRETE5_VERSION
    image: devbaclucpackages_concrete5:$CONCRETE5_VERSION
    volumes:
      - ./concrete5:/var/www/html:rw
    ports:
      - 8080:80
    networks:
      - default
    env_file:
      - ./.env

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/16

volumes:
  mariadbdata:
    driver: local
