version: '3.7'
services:
  db:
    image: mariadb:10.1-bionic
    volumes:
      - mariadbdata:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - ${MARIADB_PORT}:3306
    networks:
      default:
        aliases:
          - db

  concrete5:
    build:
      context: .
      args:
        CONCRETE5_VERSION: $CONCRETE5_VERSION
    image: devbaclucpackages_concrete5:$CONCRETE5_VERSION
    volumes:
      - html:/var/www/html:nocopy
      - vendor:/var/www/html/concrete/vendor
      - config:/var/www/html/application/config
      - files:/var/www/html/application/files
    ports:
      - 8080:80
    networks:
      - default
    env_file:
      - ./.env

    # lsyncd container to sync up host mount and named volume:
  rsync:
    image: bacluc/rsync:1.0
    build:
      context: ./docker
      dockerfile: Dockerfile-rsync
    command: tail -f /dev/null
    volumes:
      # The host mount for the shared directory:
      - ./concrete5:/mnt/html
      # The named volume for the shared directory:
      - html:/var/www/html:nocopy
      - config:/var/www/html/application/config:nocopy

  lsyncd:
    image: allthings/lsyncd
    command: -rsync /mnt/html /var/www/html
    volumes:
      # The host mount for the shared directory:
      - ./concrete5:/mnt/html:delegated
      # The named volume for the shared directory:
      - html:/var/www/html:nocopy

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/16

volumes:
  mariadbdata:
    driver: local
  html:
  vendor:
  config:
  files:
